### ISSUE TITLE
no 'Cerebellum-SUIT.nii'

### ISSUE THREAD

**Issue by chienc1** [DiedrichsenLab/cerebellar_atlases#7]
Dear All, 

 I haven't been able to find the 'Cerebellum-SUIT.nii' file in the most recent version of SUIT for MATLAB. I don't have an "atlas" directory at all.

Could you please clarify which atlas to use instead of what is listed here: http://www.diedrichsenlab.org/imaging/suit_faqs.htm or for this command suit_ROI_summarize(images,'atlas','Lobules-SUIT.nii')?

Thank you!

**Comment by jdiedrichsen** [comment]
The new SUIT toolbox does ship without the functional altasses. Just download this repository and place it (or a link to thje folder) in 
spm12/toolbox directory. 
The new release of SUIT will then find the appropriate atlases.

**Comment by chienc1** [comment]
Great, I actually already did this quite a while ago. Thank you for the reply.
