### ISSUE TITLE
Extract the cerebellum volume from Freesurfer via SUIT-cerebellum.nii 

### ISSUE THREAD

**Issue by chenycann** [DiedrichsenLab/cerebellar_atlases#9]
Hey there,
Our team is trying to extract the cerebellar volume, and we hope to remove the 28 ROIs developed from SUIT. However, we have attempted to register the atl-Anatom_space-MNI_dseg.nii to the subject space, but failed with bad registration. Is there any suggestion?

Best regrades, 
Annie

**Comment by jdiedrichsen** [comment]
Please see https://www.diedrichsenlab.org/imaging/suit_function.htm#suit_roi. 
Does the description there help?
